### ISSUE TITLE
Check the code-state model of the Near contract VM

### ISSUE THREAD

**Issue by junha1** [postech-dao/near#18]
컨트랙트의 코드와 상태가 분리되어있는지 (같은 코드를 공유하는 여러개의 인스턴스가 있는 모델인지) 서베이가 필요합니다.
참고로 Ethereum은 코드와 상태가 바인드되어있고요, CosmWasm은 따로입니다.

**Comment by Basten1209** [comment]
컨트랙트의 코드와 상태가 분리되었다는게 코드 업로드 하는 기능과 컨트랙트 인스턴스 하는 기능이 따로 있다는 말이라면 Near에서도 분리가 되어있는걸로 보입니다. 
(코드 상태가 분리되있다는게 이해가 안되서 https://medium.com/dsrv/cosmwasm-101-%EC%99%80%EC%94%80-1%ED%8E%B8-counter-%EC%BB%A8%ED%8A%B8%EB%9E%99%ED%8A%B8-%ED%86%BA%EC%95%84%EB%B3%B4%EA%B8%B0-e82ac42569ba
이 곳에서 이더와 cosmwasm 차이 설명이 되어 있어서 보고 이해를 했습니다.)

https://www.near-sdk.io/upgrading/prototyping
https://www.near-sdk.io/upgrading/production-basics

위 두 링크의 Near SDK 문서에서 보면
"The NEAR Runtime looks at your current code as well as your contract's data, which is serialized and saved on-disk. When it executes the code, it tries to match these up. If you change the code but the data stays the same, it can't figure out how to do this. Previously we "solved" this by removing old serialized data."
라고 작성 된 부분이 있는데, 컨트랙트에 대한 데이터가 따로 저장이 되고, 코드가 변경되었을 때 데이터가 유지되는 경우의 case를 handling하기 위해서 old data를 제거하여 해결한다는 내용이 있습니다. 그래서 code와 state가 분리된 것으로 보는게 맞는 것 같습니다.
확실치는 않아서 확인 한번 더 해주시면 감사하겠습니다.

**Comment by happyhappy-jun** [comment]
직접 디플로이 해서 확인해보니 니어는 코드랑 상태랑 같이 가는 모델입니다. 

Account - WASM binary - State 이 세개가 같이 묶여서 갑니다
